# params:buildDate is automatically updated by push-update.sh

baseURL = "https://summittdweller.com/blogs/mark/"
canonifyURLs = true
languageCode = "en-us"
title = "Personal Blog"
theme = "internet-weblog"
enableEmoji = true
pygmentsstyle = "emacs"
Paginate = 25
SectionPagesMenu = "main"
googleAnalytics = "UA-146526628-2"

[author]
   Handle = "Summitt Dweller"
   FirstName = "Mark"
   LastName = "McFate"
   # AboutPage = "/about"
   Location = "Toledo, Iowa"
   FlickrID = "97761917@N02"

[params]
   Description = "Personal weblog of web professional, geocacher, camper, and volunteer, Mark McFate."
   ShowCopyright = true
   RSSEnabled = true
   RSSSections = [ "Posts", "Microposts", "Photos" ]
   RSSMicropostTitles = false
   buildDate = '2020-03-15 01:04'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
  name = "Microposts"
  weight = 1
  identifier = "microposts"
  url = "/microposts/"

[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Photos"
  weight = 3
  identifier = "photos"
  url = "/photos/"

[[menu.main]]
  name = "OneTabs"
  weight = 4
  identifier = "onetabs"
  url = "/onetabs/"
